language: node_js
sudo: false
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
after_success:
  - npm run coverage
  - npm i codecov
  - codecov -f ./coverage/lcov.info
notifications:
  email:
    on_success: never
